apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: storefront
spec:
  secrets:
    - NEXT_PUBLIC_SANITY_API_VERSION
    - NEXT_PUBLIC_SANITY_DATASET
    - NEXT_PUBLIC_SANITY_PROJECT_ID
  environments:
    - name: dev
      build:
        from: feature/storefront
    - name: test
    - name: prod
  components:
    - name: web
      publicPort: http
      ports:
        - name: http
          port: 8080
  dnsAppAlias:
    environment: prod
    component: web
